#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor VGA-1 -d 1 2 3 4 5
#bspc monitor HDMI-1 -d 6 7 8 9 0 a b c d e

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a jSignPdf.jar manage=off state=floating
bspc rule -a SerproSigner.sh manage=off state=floating
bspc rule -a serpro-signer-4.0.2.jar manage=off state=floating



${HOME}/.fehbg &
xsetroot -cursor_name left_ptr &
/usr/bin/barrierc -f --no-tray --debug INFO --name heisenberg --disable-crypto [192.168.0.5]:24800 &
#setxkbmap br &
setxkbmap -layout us -variant intl &
#compton &
picom -f &
${HOME}/.config/polybar/launch.sh --forest &
#nextcloud-desktop-client.nextcloud --background &
parcellite &
wmname LG3D &
xset -dpms &
xset s 0 0 &
